version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - IMAGE_TAG=latest
      - REPO_URI=424522917744.dkr.ecr.$AWS_REGION.amazonaws.com/shoppingapp
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPO_URI
  build:
    commands:
      - echo Build started on `date`
      - mvn clean package
      - docker build -t shoppingapp:$IMAGE_TAG .
      - docker tag shoppingapp:$IMAGE_TAG $REPO_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Pushing Docker image...
      - docker push $REPO_URI:$IMAGE_TAG
      - printf '[{"name":"shoppingapp","imageUri":"%s"}]' $REPO_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json